dist: bionic
language: php
php:
- 7.2
- 7.3
- 7.4
services:
- mysql
cache:
  directories:
  - "$HOME/.composer/cache"
before_script:
- cp .env.travis .env
- sudo mysql -e 'create database testing;'
- composer self-update
- composer install --prefer-source --no-interaction --dev
- php artisan key:generate
- php artisan migrate
script:
- vendor/bin/phpstan analyse
- vendor/bin/phpunit
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: change
    on_failure: always
deploy:
  provider: heroku
  app: invoicegen-test
  api_key:
    secure: er5nkTjESCd6Li0363xmY+WGjSz+w1UppO1KuSHpkqumdEsGrd/qwqeaJihU68b3knZFxbXkN3oemQRHNu4XeJI8uFgfgC5dlxxprtmg86MEDWmDiUJo6oQEA6SBgyzdYAtjYHbZqyMgHD7kTHQT2es8dDbTr8AcQvRYKu+Fb7Ed6EiaGwUrT9vTR1eq0y+P8yG0RXfIC67+R1+CXxM794C6vSCwuDsSPkME0D9MvvAiXJ7Lr3sWxF6pE6PWy+fR6l4IBds+IGd+NCVrJbOsR4U+uxpKeFyck11tlZcahjb7JSBQczL+mmnAHYJBzSnD97TY1PdyCFqyH0U8Ez69sboKKK18qLX1x4R2bE4v+eLhJRIWPCH06VxIEpHBVQN0Ro7H9i+TE+4riEccaG+Ac9CYjFvGkLjWpxD2KQvPkt3rhvUSIclefqhsK2+Ltb9+Z5S7GOCe20iYpk7YWBX6uMsww3DuIjM02LS5GKgovJDreIRg2d3GlkJwDlx5tMKLF5nbixpFbYZuVyMM2OYSaismmI+eb9o4d+iEe3OBCofZFkSVCn6Ks6SgOjOckjDSg25CbWIHWIXqf8dhr2qvIXMDeKZ6DipazFbUraDzMt/cjcyxORaaQZL7wrW59PZ7hkCMJXK6bRilOVotbpU6TXTRvKjAU5fgng6hLZpHYwg=
  run:
    - "php artisan migrate --force"
