dist: bionic

language: php

php:
  - 7.2
  - 7.3

services:
  - mysql

cache:
  directories:
    - vendor

before_script:
  - cp .env.travis .env
  - sudo mysql -e 'create database testing;'
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpstan analyse
  - vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: change
    on_failure: always
